export const LIMPAR_INFORMACOES_USUARIO = "LIMPAR_INFORMACOES_USUARIO"
export const SALVAR_INFORMACOES_USUARIO = "SALVAR_INFORMACOES_USUARIO"
export const ATUALIZAR_TOKEN = "ATUALIZAR_TOKEN"

export const NOTIFICAR = 'NOTIFICAR'
export const REMOVER_NOTIFICACAO = 'REMOVER_NOTIFICACAO'